apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: subtrack
spec:
  rules:
    - host: subtrack.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: subtrack
                port:
                  number: 80
